"How is a code block indicated in Python?" = [
    "Indentation", "Brackets", "Key", "None of the answers is correct."
    ]

"What is the maximum length of a Python identifier?" = [
    "No fixed length is specified.", "32", "16", "128"
    ]

"Which of the following concepts is not a part of Python?" = [
    "Pointers", "Loops", "Dynamic Typing", "All answers are correct."
    ]

"Which of the following statements are used in Exception Handling in Python?" = [
    "All answers are correct.", "try", "except", "finally"   
    ]

"Which of the following types of loops are not supported in Python?" = [
    "do-while", "for", "while", "None of the answers is correct."  
    ]

"Which of the following functions converts date to corresponding time in Python?" = [
    "strptime()", "strftime()", "None of the answers is correct.", "sometime()"
    ]

"As what datatype are the *args stored, when passed into a function?" = [
    "Tuple", "List", "None of the answers is correct.", "Dictionary"
    ]

"As what datatype are the *kwargs stored, when passed into a function?" = [
    "Dictionary", "List", "None of the answers is correct.", "Tuple"
    ]

"What keyword is used in Python to raise exceptions?" = [
    "raise", "try", "goto", "except"
    ]

"Which of the following is not a valid set operation in python?" = [
    "None of the answers is correct.", "Union", "Intersection", "Difference"
    ]

"In which language is Python written?" = [
    "C", "C++", "Java", "None of the answers is correct."
    ]

"Is Python case sensitive when dealing with identifiers?" = [
    "yes", "no", "machine dependent", "None of the answers is correct."
    ]

"Which keyword is used for function in Python language?" = [
    "def", "Function", "Fun", "Define"
    ]

"Which of the following is not a core data type in Python programming?" = [
    "Class", "Tuples", "Lists", "Dictionary"
    ]

"Which one of the following is not a keyword in Python language?" = [
    "eval", "pass", "assert", "nonlocal"
    ]

"Which module in the python standard library parses options received from the command line?" = [
    "getopt", "getarg", "main", "os"
    ]

"Which of the following are valid escape sequences in Python?" = [
    "All answers are correct.", "'\\n'", "'\\t'", "'\\\\'"
    ]

"Which of the following is the correct extension of the Python file?" = [
    ".py", ".pl", ".p", ".python"
    ]

"Which of the following is false statement in python?" = [
    "None of the answers is correct.", "int(144)==144", "int('144')==144", "int(144.0)==144"
    ]

    "Python supports the creation of anonymous functions at runtime, using a construct called?" = [
    "lambda", "pi", "anonymous", "None of the answers is correct."
    ]

"What does pip stand for python?" = [
    "Preferred Installer Program", "Pip Installs Python", "Pip Installs Packages", "All answers are correct."
    ]

"Which of the following modules need to be imported to handle date time computations in Py?" = [
    "datetime", "date", "time", "timedate"
    ]

"Which of these is the definition for packages in Python?" = [
    "A folder of python modules", "A set of programs making use of Python modules", "A number of files containing Python definitions and statements", "A set of main modules"
    ]

"Which type of Programming does Python support?" = [
    "All answers are correct.", "functional programming", "structured programming", "object-oriented programming"
    ]

"Which of the following statements is used to create an empty set in Python?" = [
    "set()", "()", "[]", "{}"
]

"What is output of print(math.pow(3, 2))?" = [
    "9.0", "None", "9", "6"
]